export class OrderGuideLine{
public itemID?:String;
public chrgOrgOvrd?:String;
public vendorNo ?:String;
public dept ?:String;
public mfrID?:String;
public mfrItemNo?:String;
public averageCost?:String;
public itemDesc ?:String;
public packagingInfo?:String;
public lineNum?:String;
public supplyingAssetLoc?:String;
public orderGuide ?:String;
public vendorItemNo ?:String;
public allegianceYN?:String;
public unitOfMeasure?:String;
public org?:String;
public vendorOverrideYN?:String;
public id:String;
public parLevelQty?:String;
public estUnitCost?:String;
public itemLookUpType?:String;
public userNoteCount?:String;
public allowBackordYN?:String;
public itemTypeDesc?:String;
public buyFromLoc?:String;
public timeStamp?:String;
public hazdsMaterialYN?:String;
public itemNo?:String;
public estExtendedCost?:String;
public supplyingOrg?:String;
public chrgDeptOvrd?:String;
public cminMaxQty?:String;
public uomconvFactor?:String;
public uomdesc?:String;
public itemPicURL?:String;
public MSDSURL?:String;
public projectCode?:String;
public fundCode?:String;
public finRptFld1?:String;
public finRptFld2?:String;
public finRptFld3?:String;
public recordCount?:number;
}