export class RequisitionLine{

    public id?:String;
    public description?:String;
    public dept?:String;
    public itemID?:String;
    public vendorItemNo?:String;
    public allegianceYN?:String;
    public userNoteCount?:String;
    public itemTypeDesc?:String;
    public itemNo?:String;
    public supplyingOrg?:String;
    public tableID?:String;
    public supplyingAssetLoc?:String;
    public itemLookUpType?:String;
    public patientRegistrationYN?:String;
    public transferQtyReceived?:String;
    public statYN?:String;
    public sepPOByReqYN?:String;
    public orderedQty?:String;
    public orderedUOM?:String;
    public requisitionNo?:String;
    public reqOrg?:String;
    public issQty?:String;
    public boqty?:String;
    public reqLineNo?:String;
    public kilQty?:String;
    public messagesYN?:String;
    public alcQty?:String;
    public kilUOM?:String;
    public rcvUOM?:String;
    public alcUOM?:String;
    public bouom?:String;
    public lotTrackingYN?:String;
    public issUOM?:String;
    public altTableID?:String;
    public altRowID?:String;
    public itemPicURL?:String;
}